; NFS Heat Raise Via CTS by Kevin4e 

[Toggle]
Enable = 1                          ; Enable script (0 = false, 1 = true)

[CalculationApproach]
CalculationMode = Progressive       ; (Progressive, Absolute or Cumulative) Choose the calculation approach of the heat level. The choice depends on what you want to achieve if the CTS thresholds in the category below are not in ascending order. Read notes for detailed explanation.
PreventLowerHeat = 1                ; Prevent switching to a lower heat level. Enable if you don't want your heat level to go down when a threshold for a lower heat level is reached.

[Thresholds]
ThresholdForHeat2  = 5000           ; CTS amount to trigger Heat 2
ThresholdForHeat3  = 15000          ; CTS amount to trigger Heat 3
ThresholdForHeat4  = 50000          ; CTS amount to trigger Heat 4
ThresholdForHeat5  = 100000         ; CTS amount to trigger Heat 5
ThresholdForHeat6  = 200000         ; CTS amount to trigger Heat 6
ThresholdForHeat7  = 500000         ; CTS amount to trigger Heat 7
ThresholdForHeat8  = 1000000        ; CTS amount to trigger Heat 8
ThresholdForHeat9  = 2000000        ; CTS amount to trigger Heat 9
ThresholdForHeat10 = 5000000        ; CTS amount to trigger Heat 10

[Notes]
- Each threshold must fall within the range 0 and (2^32) - 1.
  If it doesn't, it will overflow and possibly mess up the order.

- If a CTS threshold is not consistent (e.g. 1000->2000->!500!) it will determine either of the two behaviors, depending on the calculation approach chosen:

  - Progressive: read as 'Start from the lowest. If CTS is less than the threshold for the next heat, stay at the current heat. Otherwise, move up one step.', having this situation:
                 CtsHeat2: 10000
		         CtsHeat3: 5000
                 CTS = 12000 → Heat 2 threshold is satisfied → immediately also satisfies Heat 3 (5000) → ends up at Heat 3.

  - Absolute: read as 'If CTS reaches ANY threshold for a heat level, lower heat levels are ignored.', having this situation:
                 CtsHeat8: 7000
                 CtsHeat9: 5000
                 CTS = 6000 → Heat 9 threshold is satisfied → Heat 8 is ignored → sets Heat 9.

  - Cumulative: read as 'If CTS reaches ANY threshold for a heat level, switch to it, regardless of the order', having this situation:
                 CtsHeat6: 3000
                 CtsHeat7: 1500
                 CTS = 2000 -> Heat 7 threshold is satisfied. Eventually, CTS reaches 3500, Heat 6 threshold is satisfied.
